### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [miurahr/pybcj#9]
**Is your feature request related to a problem? Please describe.**
Conda is very useful to package multiple dependencies (especially ones that contain c/c++ libraries).

**Describe the solution you'd like**
Add package to conda.

**Describe alternatives you've considered**
DIY

**Additional context**
N.A.

**Comment by miurahr** [comment]
Please check https://pypi.org/project/pybcj/0.5.2/

**Comment by sarthakpati** [comment]
Done, thanks.
